const obj={
     user_name:"ABCD",
     user_id:1234,
     user_institute:"Itview",
     user_password:"1234",
     user_info:{
        mobileno:"9834223420",
        age:45,
        add:"Pune"
     },
     user_family:["pqr","lmn","qwe"],
     user_display:()=>{
        console.log(obj.user_name);
     }
}
console.log(typeof(obj))
console.log(obj)
console.log(obj.user_info)
console.log(obj.user_family)
obj.user_display()
